export interface ModelMarketplace {
  name: string
  vrm: boolean
  live2d: boolean
  spine: boolean
  mmd: boolean
  languages: string[]
  origin: string
  url: string
  description?: string
}

export const MODEL_MARKETPLACES: ModelMarketplace[] = [
  {
    name: 'Steam Workshop',
    vrm: false,
    live2d: true,
    spine: true,
    mmd: false,
    languages: ['us'],
    origin: 'Steam',
    url: 'https://steamcommunity.com/workshop/browse/?appid=616720',
    description: 'Extensive community collection of Live2D and Spine companion models.',
  },
  {
    name: 'VChaVCha (Hololive MMD)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['us'],
    origin: 'VChaVCha',
    url: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    description: 'Curated Hololive MMD model library with official/fan models.',
  },
  {
    name: 'NicoNico 3D (MMD)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['jp'],
    origin: 'Japan',
    url: 'https://3d.nicovideo.jp/search?category=all&download_filter=all&limit=28&max_pages=100&order=1&page=1&perfect_match=1&sort=view&usable_animation=&word=MMD&word_type=tag&work_type=mmd',
    description: 'Massive archive of Japanese MMD models, stages, and motion data.',
  },
  {
    name: 'Reverse: 1999 (v1.7+)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'Storm Preservation',
    url: 'https://dasilva333.github.io/r1999-web-gallery/',
    description: 'Community web gallery archive for Reverse: 1999 Live2D models.',
  },
  {
    name: 'Eikanya Live2D Archive (4.9k+)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'Eikanya',
    url: 'https://dasilva333.github.io/live2d-eikanya-index/',
    description: 'Over 4,900 indexed Live2D models across popular games.',
  },
  {
    name: 'SillyTavern Live2D Portal (270)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'test157t',
    url: 'https://dasilva333.github.io/live2d-test157t-index/',
    description: 'Curated ready-to-use Live2D models for companion apps.',
  },
  {
    name: 'bear0830 (MMD Animations)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['us'],
    origin: 'GitHub',
    url: 'https://github.com/bear0830/mmd',
    description: 'Open source collection of MMD dances, gestures, and motion files.',
  },
  {
    name: 'Booth',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/browse/VTuber',
    description: 'Leading Japanese creator marketplace for 3D/VRM and Live2D avatars.',
  },
  {
    name: 'Booth VRMA',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/browse/3D%20Motion%20&%20Animation?sort=price_asc&tags%5B%5D=VRMA',
    description: 'Free and indie VRM animation motions (.vrma).',
  },
  {
    name: 'VGen',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://vgen.co',
    description: 'Creator commission and asset marketplace for VTuber models.',
  },
  {
    name: 'itch.io',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://itch.io/game-assets',
    description: 'Indie game assets and downloadable character models.',
  },
  {
    name: 'Gumroad',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://gumroad.com',
    description: 'Creator storefront for 3D avatars, shaders, outfits, and animations.',
  },
  {
    name: 'Ko-fi',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://ko-fi.com/shop',
    description: 'Community shops offering free and creator-supported model assets.',
  },
  {
    name: 'VRoid Hub',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://hub.vroid.com',
    description: 'Pixiv official 3D avatar sharing and showcase platform.',
  },
  {
    name: 'Sketchfab',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://sketchfab.com',
    description: 'Global 3D model repository with thousands of downloadable characters.',
  },
  {
    name: 'CGTrader',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://cgtrader.com',
    description: 'Professional 3D asset marketplace with rig-ready characters.',
  },
  {
    name: 'Nizima',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://nizima.com',
    description: 'Official Live2D marketplace for original illustrations and models.',
  },
  {
    name: 'Avatar Atelier',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://avataratelier.com',
    description: 'Directory for VTuber assets, models, and custom designs.',
  },
  {
    name: 'VTuberAvatars',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://vtuberavatars.com',
    description: 'Curated free and premium VTuber avatar collections.',
  },
]
