export type MarketplacePricing = 'free' | 'mixed' | 'paid'

export interface ModelMarketplace {
  name: string
  vrm: boolean
  live2d: boolean
  spine: boolean
  mmd: boolean
  languages: string[]
  origin: string
  url: string
  description?: string
  pricing?: MarketplacePricing
  notice?: string
}

export interface SpotlightModel {
  id: string
  name: string
  format: 'vrm' | 'live2d' | 'spine' | 'mmd'
  formatLabel?: string
  previewUrl: string
  downloadUrl: string
  sourceSiteName: string
  sourceSiteUrl?: string
  author?: string
  description?: string
}

export const SPOTLIGHT_MODELS: SpotlightModel[] = [
  {
    id: 'hololive-gura',
    name: 'Gawr Gura',
    format: 'mmd',
    formatLabel: 'MMD (.pmx)',
    previewUrl: 'https://vchavcha.com/wp-content/uploads/2024/07/Gawr-Gura_pr-img_01-683x1024.png',
    downloadUrl: 'https://drive.google.com/file/d/19W5SARdBDbsqe3ViERk3SRhtIHHpmTBq/view?usp=drive_link',
    sourceSiteName: 'VChaVCha',
    sourceSiteUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    author: 'Cover Corp',
    description: 'Official Hololive English -Myth- 3D model.',
  },
  {
    id: 'hololive-baelz',
    name: 'Hakos Baelz',
    format: 'mmd',
    formatLabel: 'MMD (.pmx)',
    previewUrl: 'https://vchavcha.com/wp-content/uploads/2024/07/Hakos-Baelz_pr-img_01-593x1024.png',
    downloadUrl: 'https://3d.nicovideo.jp/works/td94990',
    sourceSiteName: 'NicoNico 3D / VChaVCha',
    sourceSiteUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    author: 'Cover Corp',
    description: 'Official Hololive English -Council- 3D model.',
  },
  {
    id: 'hololive-ina',
    name: 'Ninomae Ina\'nis',
    format: 'mmd',
    formatLabel: 'MMD (.pmx)',
    previewUrl: 'https://vchavcha.com/wp-content/uploads/2024/07/4003_Ninomae-Inanis-768x922.png',
    downloadUrl: 'https://3d.nicovideo.jp/works/td88804',
    sourceSiteName: 'NicoNico 3D / VChaVCha',
    sourceSiteUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    author: 'Cover Corp',
    description: 'Official Hololive English -Myth- 3D model.',
  },
  {
    id: 'hololive-mococo',
    name: 'Mococo Abyssgard',
    format: 'mmd',
    formatLabel: 'MMD (.pmx)',
    previewUrl: 'https://vchavcha.com/wp-content/uploads/2024/07/Mococo-Abyssgard_pr-img_01-593x1024.png',
    downloadUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    sourceSiteName: 'VChaVCha',
    sourceSiteUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    author: 'Cover Corp',
    description: 'Official Hololive English -Advent- 3D model.',
  },
  {
    id: 'hololive-pekora',
    name: 'Usada Pekora',
    format: 'mmd',
    formatLabel: 'MMD (.pmx)',
    previewUrl: 'https://vchavcha.com/wp-content/uploads/2024/07/Usada-Pekora_pr-img_01-510x1024.png',
    downloadUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    sourceSiteName: 'VChaVCha',
    sourceSiteUrl: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    author: 'Cover Corp',
    description: 'Official Hololive 3rd Generation 3D model.',
  },

  // --- VRoid Hub Free VRM Models (Initial VRM Set) ---
  {
    id: 'vroid-sunna',
    name: 'SUNNA (Tea Break)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://vroid-hub.pximg.net/c/300x400_a2_g5/images/full_body_images/5419722/3595642509134764371.png',
    downloadUrl: 'https://hub.vroid.com/en/characters/9068578537763345614/models/5954634722265640249',
    sourceSiteName: 'VRoid Hub',
    sourceSiteUrl: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    description: 'Anime girl 3D companion avatar, afternoon tea theme.',
  },
  {
    id: 'vroid-joker',
    name: 'Joker (Vampire Goth)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://vroid-hub.pximg.net/c/300x400_a2_g5/images/full_body_images/3268928/6953129382509305525.png',
    downloadUrl: 'https://hub.vroid.com/en/characters/1196921191112617542/models/6626618204806071170',
    sourceSiteName: 'VRoid Hub',
    sourceSiteUrl: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    description: 'Gothic vampire themed 3D character avatar in VRM format.',
  },
  {
    id: 'vroid-you-canaria',
    name: 'You Canaria (ヨウ・カナリア)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://vroid-hub.pximg.net/c/300x400_a2_g5/images/full_body_images/5775353/3069435284698051203.png',
    downloadUrl: 'https://hub.vroid.com/en/characters/8296139918079963140/models/768260972038234419',
    sourceSiteName: 'VRoid Hub',
    sourceSiteUrl: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    description: 'Original canary themed anime 3D companion avatar in VRM format.',
  },
  {
    id: 'vroid-cissia',
    name: 'CISSIA',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://vroid-hub.pximg.net/c/300x400_a2_g5/images/full_body_images/5419722/2977308082131288923.png',
    downloadUrl: 'https://hub.vroid.com/en/characters/1696519816565669543/models/5096414703124948478',
    sourceSiteName: 'VRoid Hub',
    sourceSiteUrl: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    author: '꺳키위',
    description: 'Stylized anime character 3D avatar in VRM format.',
  },
  {
    id: 'vroid-daring-heart',
    name: 'Daring Heart (デアリングハート)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://vroid-hub.pximg.net/c/300x400_a2_g5/images/full_body_images/4689647/3872157376473113083.png',
    downloadUrl: 'https://hub.vroid.com/en/characters/5687292021833979291/models/4364211136023539866',
    sourceSiteName: 'VRoid Hub',
    sourceSiteUrl: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    author: 'Uma Musume: Pretty Derby',
    description: 'Uma Musume: Pretty Derby Daring Heart 3D companion avatar in VRM format.',
  },

  // --- Rigged 3D / GLB (CGTrader Free Rigged Portal) ---
  {
    id: 'cgtrader-beach-boy',
    name: 'Stylized Beach Boy',
    format: 'vrm',
    formatLabel: 'GLB / Rigged 3D',
    previewUrl: 'https://img-new.cgtrader.com/items/7152135/1e0440a42d/stylized-beach-male-character-cartoon-boy-rigged-and-animated-3d-model-1e0440a42d.webp',
    downloadUrl: 'https://www.cgtrader.com/free-3d-models/character/man/stylized-beach-male-character-cartoon-boy-rigged-and-animated',
    sourceSiteName: 'CGTrader',
    sourceSiteUrl: 'https://www.cgtrader.com/rigged-3d-models?file_types%5B%5D=117&free=1&rigged=1',
    author: 'CGTrader Community',
    description: 'Stylized cartoon boy character, fully rigged and animated.',
  },
  {
    id: 'cgtrader-anime-girl',
    name: 'Kawaii Anime Girl',
    format: 'vrm',
    formatLabel: 'GLB / Rigged 3D',
    previewUrl: 'https://img-new.cgtrader.com/items/6318871/96b3be3215/rigged-kawaii-anime-girl-casual-style-3d-model-3d-model-96b3be3215.jpg',
    downloadUrl: 'https://www.cgtrader.com/free-3d-models/character/woman/rigged-kawaii-anime-girl-casual-style-3d-model',
    sourceSiteName: 'CGTrader',
    sourceSiteUrl: 'https://www.cgtrader.com/rigged-3d-models?file_types%5B%5D=117&free=1&rigged=1',
    author: 'CGTrader Community',
    description: 'Rigged anime girl character in casual streetwear style.',
  },
  {
    id: 'cgtrader-female-024',
    name: 'Humanoid Female 024',
    format: 'vrm',
    formatLabel: 'GLB / Humanoid 3D',
    previewUrl: 'https://img-new.cgtrader.com/items/2579446/d2bee6c78a/unity-humanoid-model-female-024-3d-model-d2bee6c78a.jpg',
    downloadUrl: 'https://www.cgtrader.com/free-3d-models/character/woman/unity-humanoid-model-female-024',
    sourceSiteName: 'CGTrader',
    sourceSiteUrl: 'https://www.cgtrader.com/rigged-3d-models?file_types%5B%5D=117&free=1&rigged=1',
    author: 'CGTrader Community',
    description: 'Rigged Unity humanoid 3D female avatar ready for animation.',
  },

  // --- Live2D Models (Ko-fi Free Creator Portals) ---
  {
    id: 'kofi-dg-cyberpunk-maid',
    name: 'Cyberpunk Maid',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/da0867fc-c98d-4421-afa2-1556434aa03c_kbn-w.png',
    downloadUrl: 'https://ko-fi.com/s/a8b653d2e8',
    sourceSiteName: 'DG Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/dgstudio/shop/free%EF%BC%81',
    author: 'DG Studio',
    description: 'Cyberpunk anime maid complete Live2D avatar.',
  },
  {
    id: 'kofi-dg-redgrave',
    name: 'Redgrave',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/d34a2715-6616-4648-bf3d-0006fd881d19_%e5%90%b8%e8%a1%80%e9%ac%bc-%e5%b9%85%e5%9b%be.png',
    downloadUrl: 'https://ko-fi.com/s/92326389e7',
    sourceSiteName: 'DG Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/dgstudio/shop/free%EF%BC%81',
    author: 'DG Studio',
    description: 'Gothic vampire themed Live2D model (Free to try).',
  },
  {
    id: 'kofi-dg-sheli',
    name: 'Sheli (Snow Leopard)',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/61e56c6b-aa86-449d-a066-5cacb4304a04_sheli-%e5%b9%85%e5%9b%be.jpg',
    downloadUrl: 'https://ko-fi.com/s/d38a69fa43',
    sourceSiteName: 'DG Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/dgstudio/shop/free%EF%BC%81',
    author: 'DG Studio',
    description: 'Snow leopard kemonomimi Live2D model (Free to try).',
  },
  {
    id: 'kofi-dg-marth7',
    name: 'March 7th',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/b9f97b84-48e7-44e3-931d-6a415c4974b5_fangka1.png',
    downloadUrl: 'https://ko-fi.com/s/867102f774',
    sourceSiteName: 'DG Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/dgstudio/shop/free%EF%BC%81',
    author: 'DG Studio',
    description: 'Honkai: Star Rail inspired March 7th Live2D model.',
  },
  {
    id: 'kofi-kyoki-noya',
    name: 'Noya',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/267f1568-54a1-402f-b5a9-dcc7efac1653_%e8%af%ba%e4%ba%9a%e6%96%b9%e5%8d%a1.jpg',
    downloadUrl: 'https://ko-fi.com/s/d089989657',
    sourceSiteName: 'Kyoki Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/kyokistudio/shop/free%E2%AD%90%EF%B8%8F',
    author: 'Kyoki Studio',
    description: 'Original VTuber character Live2D avatar (Free Edition).',
  },
  {
    id: 'kofi-kyoki-alexia',
    name: 'Alexia',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://storage.ko-fi.com/cdn/useruploads/display/3abd0cd9-2259-4c4e-80aa-287da463a804_poipic.png',
    downloadUrl: 'https://ko-fi.com/s/58b175ee12',
    sourceSiteName: 'Kyoki Studio (Ko-fi)',
    sourceSiteUrl: 'https://ko-fi.com/kyokistudio/shop/free%E2%AD%90%EF%B8%8F',
    author: 'Kyoki Studio',
    description: 'Ready-to-use anime Live2D avatar.',
  },

  // --- itch.io Free Community Models ---
  {
    id: 'itch-garnet',
    name: 'Garnet',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://img.itch.zone/aW1nLzkxNjQxNTcuZ2lm/315x250%23c/ug0biF.gif',
    downloadUrl: 'https://salmon-snake.itch.io/garnet-live2d-a-free-model',
    sourceSiteName: 'itch.io',
    sourceSiteUrl: 'https://itch.io/game-assets/free/tag-live2d',
    author: 'Salmon Snake',
    description: 'Free animated anime girl Live2D companion model.',
  },
  {
    id: 'itch-lucie',
    name: 'Lucie (Simple+)',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://img.itch.zone/aW1nLzEzODA4MTMxLnBuZw==/347x500/jC8Tj6.png',
    downloadUrl: 'https://hamstercrumbs.itch.io/lucie2d',
    sourceSiteName: 'itch.io',
    sourceSiteUrl: 'https://itch.io/game-assets/free/tag-live2d',
    author: 'HamsterCrumbs',
    description: 'Sample anime girl Live2D avatar, rigged and ready to use.',
  },
  {
    id: 'itch-urban-simple',
    name: 'Urban Simple V3',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://img.itch.zone/aW1nLzI2NzgwNzI2LnBuZw==/315x250%23c/d1XGbd.png',
    downloadUrl: 'https://xcapox.itch.io/urban-simple',
    sourceSiteName: 'itch.io',
    sourceSiteUrl: 'https://itch.io/game-assets/free/tag-vrm',
    author: 'xcapox',
    description: 'Modern stylized urban 3D character avatar in VRM format.',
  },
  {
    id: 'itch-alice-chan',
    name: 'Alice Chan',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://img.itch.zone/aW1hZ2UvMTYzNjM1Ny85NjIxMzc5LnBuZw==/794x1000/hrEGWc.png',
    downloadUrl: 'https://yuna0x0.itch.io/alice-chan',
    sourceSiteName: 'itch.io',
    sourceSiteUrl: 'https://itch.io/game-assets/free/tag-vrm',
    author: 'Yuna',
    description: 'Anime girl 3D companion avatar in VRM format.',
  },

  // --- Booth Free Live2D Models ---
  {
    id: 'booth-witch',
    name: 'Witch (魔女)',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/12bc9ed4-4f56-4b8f-9741-772cab0a5540/i/6499774/7ad3d769-3bb6-485b-a526-f864b346fa61_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/6499774',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Anime witch complete Live2D avatar, VTS compatible.',
  },
  {
    id: 'booth-ice-girl',
    name: 'Ice Girl',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/7852de40-0e15-4aaa-a153-c87a69b871e1/i/5975192/debd448b-024b-4ea1-92d5-555f7c3df80d_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/5975192',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Fantasy ice girl anime Live2D character model.',
  },
  {
    id: 'booth-anya-forger',
    name: 'Anya Forger',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/b3e2ca7f-ad77-41b7-849d-7e2beff5b285/i/5247208/8eaabd1d-721f-4491-b3ff-78d8a1eff606_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/5247208',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'SPY x FAMILY Anya Forger fan Live2D companion model.',
  },
  {
    id: 'booth-maid-cat-girl',
    name: 'Maid Cat Girl',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/fc691dc2-8c1f-49b7-a148-314bce631478/i/5047582/e291c175-59fb-4837-b785-b614256acc41_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/5047582',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Nekomimi maid companion Live2D model, fully rigged.',
  },
  {
    id: 'booth-usahime',
    name: 'Usahime (兎姫)',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/b3d67d48-19b5-4475-851e-7c8524773874/i/3072192/64e85726-0003-4d1b-a8f0-4642321aa4fa_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/3072192',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Lolita apron dress bunny girl anime Live2D model.',
  },
  {
    id: 'booth-racoon',
    name: 'Racoon',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/c78b0c21-62e8-4b57-8863-3abb82408b16/i/3910486/9d24f5ac-8033-423b-97bf-e8fa1e4b58b0_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/3910486',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Chibi racoon companion Live2D model, VTS compatible.',
  },
  {
    id: 'booth-allium',
    name: 'Allium',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/5ecf35cf-4d34-4799-87d9-9ae9d9a7f780/i/5879420/d1109f13-8353-4dcc-861c-b26c25ea559b_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/5879420',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Anime girl Live2D avatar, VTS compatible.',
  },
  {
    id: 'booth-ff01',
    name: 'FF-01',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/de57f5a9-a5d6-4ca1-a696-d4875ddd523c/i/3489618/0b90c58d-cf04-4d01-9255-452770bf16ba_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/3489618',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Fully rigged futuristic anime girl Live2D avatar.',
  },
  {
    id: 'booth-fu-xuan',
    name: 'Fu Xuan (符玄)',
    format: 'live2d',
    formatLabel: 'Live2D (.model3.json)',
    previewUrl: 'https://booth.pximg.net/590dd8a3-a0e6-4ff9-8da0-e6c3577fed93/i/5241415/dfe8f997-f2cd-467b-93f0-85b85a178f95_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/5241415',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Honkai: Star Rail Fu Xuan fan Live2D companion avatar.',
  },

  // --- Booth Free VRM 3D Models ---
  {
    id: 'booth-calmelo',
    name: 'Calmelo (きゃるめろ)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://booth.pximg.net/d6d77404-a627-4a99-9248-82a67e292629/i/1583453/9c62bec5-a04f-47b7-be3e-db62258edaf9_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/1583453',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Original anime 3D companion avatar in VRM format.',
  },
  {
    id: 'booth-godzilla-chan',
    name: 'Godzilla-Chan (ゴジラちゃん)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://booth.pximg.net/9b8eda75-ae02-4c40-97af-1800e0c38b86/i/2867960/dda6d905-3a56-4fa9-abb8-9675adcd8740_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/2867960',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Godzilla-Chan cute monster anime avatar in VRM format.',
  },
  {
    id: 'booth-pochi',
    name: 'Pochi (ポチ)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://booth.pximg.net/bbcf8d8d-e1eb-4154-bac8-0657193e753c/i/6283622/00d7c7ff-1f63-4cea-966b-383066c9a040_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/6283622',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Cute stylized chibi avatar in VRM/VRChat format.',
  },
  {
    id: 'booth-raddollv3',
    name: 'RadDollV3',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://booth.pximg.net/3c39b721-63d9-4193-a883-507b13ff6ebc/i/3741802/afa3bdb2-cb86-4c1b-9624-be6a60052e0e_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/3741802',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Anime doll avatar designed for VR and companion applications.',
  },
  {
    id: 'booth-kyoko-riku',
    name: 'Kyoko Riku (響狐リク)',
    format: 'vrm',
    formatLabel: 'VRM (3D)',
    previewUrl: 'https://booth.pximg.net/b9d3bdc9-8b02-4ce8-b8ad-c9def375cd4d/i/1148939/22d3f7c6-7f57-4532-b501-87312a0d6a0a_base_resized.jpg',
    downloadUrl: 'https://booth.pm/en/items/1148939',
    sourceSiteName: 'Booth',
    sourceSiteUrl: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Original fox anime 3D companion avatar in VRM format.',
  },

  // --- Steam Workshop Live2D Models ---
  {
    id: 'steam-azur-lane-ayanami',
    name: 'Ayanami (碧蓝航线_niconico绫波)',
    format: 'live2d',
    formatLabel: 'Live2D (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/921416923031488607/6CCD19E9186179C6E8FDA6690B67C7FA0B4C1C75/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=1242187210',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=R-15&requiredtags%5B%5D=Live2D',
    author: 'Steam Workshop',
    description: 'Azur Lane niconico Ayanami Live2D companion model (requires .lpk extraction).',
  },
  {
    id: 'steam-destiny-child',
    name: 'Destiny Child (天命之子)',
    format: 'live2d',
    formatLabel: 'Live2D (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/2030596594503194455/7971135D33EBB9888F2637666DA6188E14B2DD11/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=2933423823',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=R-15&requiredtags%5B%5D=Live2D',
    author: 'Steam Workshop',
    description: 'Destiny Child animated Live2D companion model (requires .lpk extraction).',
  },
  {
    id: 'steam-destiny-child-122',
    name: 'Destiny Child Auto 122 (全自动版122)',
    format: 'live2d',
    formatLabel: 'Live2D (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/2305344642146736676/746779133333C7A8B84A53A132E61EDE44624616/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3131884693',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=R-15&requiredtags%5B%5D=Live2D',
    author: 'Steam Workshop',
    description: 'Destiny Child auto-animated Live2D avatar (requires .lpk extraction).',
  },

  // --- Steam Workshop Spine Models ---
  {
    id: 'steam-nikke-c491',
    name: 'NIKKE Auto c491 (全自动版c491)',
    format: 'spine',
    formatLabel: 'Spine (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/2490006808487073451/FF4CD8CBD54A97221B129CACF9985E032FE60E61/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3259384997',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=Spine&requiredtags%5B%5D=R-15',
    author: 'Steam Workshop',
    description: 'Goddess of Victory: Nikke animated Spine character avatar (requires .lpk extraction).',
  },
  {
    id: 'steam-nikke-sora',
    name: '[NIKKE] Sora Spring Flight (Alt)',
    format: 'spine',
    formatLabel: 'Spine (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/14994280306756354695/55E5CFCDF8EBA78565DE8449A1F43923E732C751/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3714446785',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=Spine&requiredtags%5B%5D=R-15',
    author: 'Steam Workshop',
    description: 'Goddess of Victory: Nikke - Sora Spring Flight animated Spine avatar (requires .lpk extraction).',
  },
  {
    id: 'steam-nikke-c313',
    name: 'NIKKE Auto c313 (全自动版c313)',
    format: 'spine',
    formatLabel: 'Spine (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/5949888524148642661/E35EE4D2598BFDC1D0633087CF58ED650B54B233/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3168609408',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=Spine&requiredtags%5B%5D=R-15',
    author: 'Steam Workshop',
    description: 'Goddess of Victory: Nikke animated Spine character avatar (requires .lpk extraction).',
  },
  {
    id: 'steam-cross-core-nagling',
    name: 'Cross Core - Nagling Stage ([交错战线] 纳格陵•悦动舞台)',
    format: 'spine',
    formatLabel: 'Spine (.lpk)',
    previewUrl: 'https://images.steamusercontent.com/ugc/59207469228109811/05BBE9C1EECCFF3D87C81F425DA029520AB820D9/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true',
    downloadUrl: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3397659815',
    sourceSiteName: 'Steam Workshop',
    sourceSiteUrl: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=Spine&requiredtags%5B%5D=R-15',
    author: 'Steam Workshop',
    description: 'Cross Core (交错战线) - Nagling animated Spine companion avatar (requires .lpk extraction).',
  },
]

export const MODEL_MARKETPLACES: ModelMarketplace[] = [
  // --- 100% Free Community Archives ---
  {
    name: 'VChaVCha (Hololive MMD)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['us'],
    origin: 'VChaVCha',
    url: 'https://vchavcha.com/en/free-resources/hololive-mmd-download/',
    description: 'Curated Hololive MMD model library with official and fan-made character models.',
    pricing: 'free',
  },
  {
    name: 'NicoNico 3D (MMD)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['jp'],
    origin: 'Japan',
    url: 'https://3d.nicovideo.jp/search?category=all&download_filter=all&limit=28&max_pages=100&order=1&page=1&perfect_match=1&sort=view&usable_animation=&word=MMD&word_type=tag&work_type=mmd',
    description: 'Massive archive of Japanese MMD models, stages, accessories, and motion files.',
    pricing: 'free',
  },
  {
    name: 'Reverse: 1999 (v1.7+)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'Storm Preservation',
    url: 'https://dasilva333.github.io/r1999-web-gallery/',
    description: 'Community web gallery archive for Reverse: 1999 Live2D models.',
    pricing: 'free',
  },
  {
    name: 'Eikanya Live2D Archive (4.9k+)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'Eikanya',
    url: 'https://dasilva333.github.io/live2d-eikanya-index/',
    description: 'Over 4,900 indexed Live2D models across popular mobile and indie games.',
    pricing: 'free',
  },
  {
    name: 'SillyTavern Live2D Portal (270)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['cn', 'en'],
    origin: 'test157t',
    url: 'https://dasilva333.github.io/live2d-test157t-index/',
    description: 'Curated collection of ready-to-use Live2D models for companion and assistant apps.',
    pricing: 'free',
  },
  {
    name: 'bear0830 (MMD Animations)',
    vrm: false,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['us'],
    origin: 'GitHub',
    url: 'https://github.com/bear0830/mmd',
    description: 'Open-source collection of MMD dances, gestures, facial expressions, and motion files.',
    pricing: 'free',
  },
  {
    name: 'DG Studio (Ko-fi Free Live2D)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'Ko-fi',
    url: 'https://ko-fi.com/dgstudio/shop/free%EF%BC%81',
    description: 'Creator shop featuring a dedicated free library of full anime Live2D avatars and tryouts.',
    pricing: 'free',
    notice: 'Free Shop Portal',
  },
  {
    name: 'Kyoki Studio (Ko-fi Free Live2D)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'Ko-fi',
    url: 'https://ko-fi.com/kyokistudio/shop/free%E2%AD%90%EF%B8%8F',
    description: 'Creator shop featuring free starter editions of high-quality anime Live2D models.',
    pricing: 'free',
    notice: 'Free Shop Portal',
  },
  {
    name: 'itch.io (Free VRM 3D)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'itch.io',
    url: 'https://itch.io/game-assets/free/tag-vrm',
    description: 'Curated tag portal for free indie 3D avatar and character models in VRM format.',
    pricing: 'free',
    notice: 'Free Tagged Portal',
  },
  {
    name: 'itch.io (Free Live2D)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'itch.io',
    url: 'https://itch.io/game-assets/free/tag-live2d',
    description: 'Curated tag portal for free community 2D avatars and sample models in Live2D format.',
    pricing: 'free',
    notice: 'Free Tagged Portal',
  },
  {
    name: 'Booth (Free Live2D)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/search/live2d?max_price=0',
    description: 'Over 2,000 free community Live2D avatars, outfits, and VTuber models on Booth.',
    pricing: 'free',
    notice: '2,000+ Free Items',
  },
  {
    name: 'Booth (Free VRM 3D)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/search/vrm?max_price=0',
    description: 'Curated portal for free 3D VRM avatar models and characters on Booth.',
    pricing: 'free',
    notice: 'Free Filter Pre-applied',
  },
  {
    name: 'VRoid Hub (Free VRM Models)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://hub.vroid.com/en/models?is_other_users_available=1&is_downloadable=1',
    description: 'Pixiv VRoid Hub catalog pre-filtered for free, directly downloadable 3D VRM avatar models.',
    pricing: 'free',
    notice: 'Free Download Filter',
  },
  {
    name: 'Steam Workshop (Spine Models)',
    vrm: false,
    live2d: false,
    spine: true,
    mmd: false,
    languages: ['us', 'cn', 'jp'],
    origin: 'Steam',
    url: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=Spine&requiredtags%5B%5D=R-15',
    description: 'Over 4,700 Spine companion models on Steam Workshop (Live2DViewerEX). Models download as .lpk packages.',
    pricing: 'free',
    notice: 'Live2DViewerEX (.lpk) • R-15 Filtered',
  },
  {
    name: 'Steam Workshop (Live2D Models)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us', 'cn', 'jp'],
    origin: 'Steam',
    url: 'https://steamcommunity.com/workshop/browse/?appid=616720&browsesort=trend&section=readytouseitems&p=1&num_per_page=30&days=7&requiredtags%5B%5D=R-15&requiredtags%5B%5D=Live2D',
    description: 'Over 6,200 Live2D companion models on Steam Workshop (Live2DViewerEX). Models download as .lpk packages.',
    pricing: 'free',
    notice: 'Live2DViewerEX (.lpk) • R-15 Filtered',
  },
  {
    name: 'Steam LPK Packager & Extractor',
    vrm: false,
    live2d: true,
    spine: true,
    mmd: false,
    languages: ['us'],
    origin: 'GitHub',
    url: 'https://github.com/dasilva333/steam-lpk-packager',
    description: 'Open-source companion tool to download, unpack, and convert Steam Workshop Live2DViewerEX .lpk files for AIRI.',
    pricing: 'free',
    notice: 'Companion Extractor Tool',
  },

  // --- Creator Marketplaces, Stores & Commissions ---
  {
    name: 'Booth',
    vrm: true,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/browse/VTuber',
    description: 'Leading Japanese creator marketplace for 3D/VRM and Live2D avatars and outfits.',
    pricing: 'mixed',
  },
  {
    name: 'Booth VRMA',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://booth.pm/en/browse/3D%20Motion%20&%20Animation?sort=price_asc&tags%5B%5D=VRMA',
    description: 'Free and indie VRM animation motions (.vrma) for skeletal body gestures.',
    pricing: 'mixed',
  },
  {
    name: 'Gumroad (3D Avatars)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: true,
    languages: ['us'],
    origin: 'USA',
    url: 'https://gumroad.com/3d/avatars',
    description: 'Curated 3D avatar index. Note: models are commonly VRChat UnityPackages requiring manual conversion to VRM/MMD.',
    pricing: 'mixed',
    notice: 'VRChat UnityPackage (DIY)',
  },
  {
    name: 'Sketchfab',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://sketchfab.com',
    description: 'Global 3D model repository with thousands of downloadable and purchasable characters.',
    pricing: 'mixed',
  },
  {
    name: 'CGTrader (Free Rigged 3D)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://www.cgtrader.com/rigged-3d-models?file_types%5B%5D=117&free=1&rigged=1',
    description: 'Direct portal of free, rigged 3D humanoid character models in GLB/GLTF format.',
    pricing: 'mixed',
    notice: 'Free Rigged Portal',
  },
  {
    name: 'Nizima',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['jp', 'us'],
    origin: 'Japan',
    url: 'https://nizima.com',
    description: 'Official Live2D marketplace for illustrations, ready-to-use models, and creator commissions.',
    pricing: 'paid',
  },
  {
    name: 'VTuberAvatars',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://vtuberavatars.com',
    description: 'Curated free and premium VTuber avatar collections.',
    pricing: 'mixed',
  },
  {
    name: 'VGen (3D Models)',
    vrm: true,
    live2d: false,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://vgen.co/catalogue/3d-models',
    description: 'Creator commission catalogue for custom 3D avatars, outfit modeling, and accessories.',
    pricing: 'paid',
  },
  {
    name: 'VGen (2D Avatars)',
    vrm: false,
    live2d: true,
    spine: false,
    mmd: false,
    languages: ['us'],
    origin: 'USA',
    url: 'https://vgen.co/catalogue/2d-avatars',
    description: 'Creator commission catalogue for custom Live2D model art, cutting, and rigging.',
    pricing: 'paid',
  },
]
